contentful/contentful.net

Contentful.Core/Models/Management/IFieldValidation.cs

Currently RangeValidators are serializing as SizeValidators when being created.

Fix issue where range is treated as a size validator

---

Contentful.Core/ContentfulManagementClient.cs

Currently description is not being set on a content type when using the management API to create content types

Fix issue where description is not being set

---

Contentful.Core/Configuration/ValidationsJsonConverter.cs
Contentful.Core/Models/Location.cs
Contentful.Core/Models/Management/IFieldValidation.cs
Contentful.Core/Models/Management/SystemFileSizeUnits.cs

When trying to parse the Json of the size and range validators, if the JTokenType is null (e.g. the json looks something like this: { size: { min: null, max: 50 } }, there would be an exception thrown by the int.Parse. I added a check for the JTokenType before executing the int.Parse.
I also noticed when trying to get a content type for which one of the missing validators was defined, there would be an exception thrown from the
`return Activator.CreateInstance(objectType);`
since you cannot create a type of an interface, in this case IFieldValidator.

Resolved JTokenType.Null exception and Added missing validators

---

Contentful.Core/Models/Asset.cs

This is an inconsistency as you either have all the fields mapped to the localized models like the following example, or you remove the JsonProperty as I did. This is creating an issue for me as ALL my fields are localize and I cannot directly map the `SynedAsset` to the `Asset`
```
public class Asset : IContentfulResource
{
/// <summary>
/// Common system managed metadata properties.
/// </summary>
[JsonProperty("sys")]
public SystemProperties SystemProperties { get; set; }
/// <summary>
/// The description of the asset.
/// </summary>
public string Description { get; set; }
/// <summary>
/// The title of the asset.
/// </summary>
public string Title { get; set; }
/// <summary>
/// Encapsulates information about the binary file of the asset.
/// </summary>
public File File { get; set; } …
```

Remove JsonProperty Mapping for "file"

---

README.md

Changes:
1. Since there is RTM version `1.0.0`, I removed the `-prerelease` argument from Package Manager command. 
2. Since the library is targeting .NET Standard, I added second option to install the NuGet package via .NET CLI.
3. To make all code example consistent, I placed open brace on a new line.
4. Updated project's name to `Contentful Client Library` make it clear. If you don't like it, maybe `Contentful SDK for .NET` then.

Update README.md file with a couple changes to make it looks better.

---

Contentful.Core/IContentfulClient.cs

It would be good to have the IContentTypeResolver on the the IContentfulClient interface so that you can inject IContentClient with DI and not have to deal with the implementation class.

Add IContentTypeResolver to IContentfulClient

---

Contentful.AspNetCore/Contentful.AspNetCore.csproj
Contentful.Core/Contentful.Core.csproj

The [nuget.org](https://www.nuget.org/) doesn't current show the link `Source Code` for NuGet package `contentful.csharp` for [Source Code Link](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html) feature.
The reason is because of the incorrect value in the element `RepositoryUrl`. It starts with `git://` instead of `https://`.
After merging the fix, you should re-upload the package to bring updated `nuspec`.

Fix repository URL for Source Code Link feature.

---

Contentful.Core.Tests/ContentfulManagementClientTests.cs
Contentful.Core.Tests/JsonFiles/ContenttypesCollectionManagement.json
Contentful.Core/Configuration/ValidationsJsonConverter.cs
Contentful.Core/Models/Management/IFieldValidation.cs

Hi there.
The production API was breaking on GetContentTypes.  After some investigation it turned out that the deserialization from JSON to the ContentType wasn't working for rich text validations because it wasn't set up in the API.
I added the two additional validations needed and updated associated unit tests and content to make GetContentTypes work.  I didn't investigate pushing content types up so this may be a scenario that needs further investigation.
Thanks

added deserialization support for validation types that use rich text

---

Contentful.Core/IContentfulClient.cs

Querystring is listed as optional in documentation but is currently only optional in the ContentfulClient implementation, not the interface IContentfulClient.

Fix optional querystring for GetAsset in IContentfulClient

---

Contentful.Core.Tests/Models/Rendering/HtmlRenderTests.cs
Contentful.Core/Models/Authoring.cs

These are automatically added by Contentful and it [can cause headaches](https://github.com/contentful/rich-text/issues/126).
I also added a check for a null or empty document because in my experience with the current Contentful package, I noticed there were exceptions if a document came back null or with no content.

Added html renderer support for omitting <p> tags inside <li> tags

---

Contentful.Core/Models/Authoring.cs

I need to be able to get hold of the Renderer Collection for use in a custom link renderer, so this will expose it and allow it to be used

Exposing Renderers so they can be used in Custom Renderers

---

Contentful.Core/ContentfulManagementClient.cs
Contentful.Core/IContentfulManagementClient.cs

As it is there is no way to retrieve entries for locale by `spaceId` unless you create a different client. The fact that `GetEntriesForLocale` accepts a `spaceId` is also misleading since it is not used to retrieve the content with it.

Make `GetEntriesCollection` accept spaceId

---

Contentful.Core/ContentfulManagementClient.cs
Contentful.Core/IContentfulManagementClient.cs

Particularly [these](https://github.com/contentful/contentful.net/pull/250/files#diff-1584378cf2f8101a0c15a8db1c4034e8d9d3e983c7e95407c8498b7bd508989bR2105) changes fix a bug. 
The change to `ManagementAsset` can be reverted

Fix GetAssetsCollection by passing spaceId to CreateOrUpdateAsset

---

Contentful.Core.Tests/ContentfulClientTests.cs
Contentful.Core/ContentfulClient.cs

This commit address issue [#261](https://github.com/contentful/contentful.net/issues/261) to update
`GetEntry<T>` with documentation and `GetEntries<T>`.
In order to do this, a check on the generic parameter to only flatten when T is not Entry<U> has been added.  Otherwise, the implementation goes back to the existing one to push back the fields to the same level as system and metadata properties.
All tests pass and an additional test demonstrating update behavior has been added.

Issue #261 consistency of Entry<T> when fetching single entry by id.

---

Contentful.Core.Tests/Contentful.Core.Tests.csproj
Contentful.Core.Tests/ContentfulClientTests.cs
Contentful.Core.Tests/Extensions/JsonConversionExtensionsTests.cs
Contentful.Core.Tests/JsonFiles/EmbargoAssetKey.json
Contentful.Core/ContentfulClient.cs
Contentful.Core/ContentfulManagementClient.cs
Contentful.Core/Extensions/JsonConversionExtensions.cs
Contentful.Core/IContentfulClient.cs
Contentful.Core/Models/EmbargoedAssetKey.cs

This commit partially addresses issue [267](https://github.com/contentful/contentful.net/issues/267) for supporting embargoed assets. 
The following was done:
- Add a new model representing the embargo asset key, policy and
expiration
- Add a new method CreateEmbargoedAssetKey which generates a new key with
a given time to expiry, using the preview or delivery API.
- Added a private equivalent PUT analog to the GET function
- Moved ConvertObjectToStringJson to an extension method so that it can
be used in the PUT method for both the content and management clients.
- Added unit tests for the moved extension method.
- Added unit tests for the CreateEmbargoedAssetKey method

 New method for creating embargoed asset keys using delivery/preview API

---

Contentful.Core/Images/ImageUrlBuilder.cs

Quality is supported on webp images by contentful API, but was removed

Allow quality parameter for webp images

---

Contentful.Core/Configuration/ContentJsonConverter.cs

This fix solves the following error we are getting
`Newtonsoft.Json.JsonReaderException: 'The reader's MaxDepth of 64 has been exceeded. Path 'items[0].content.content.content[54].content[0].content[0].content[0].data.target.internalPage.content.content.content[57].content[1].content[0].content[1].data.target.internalPage.content.content.content[53].content[2].content[0].content[1].data.target.internalPage.content.content.content[54].content[3].content[0].content[0].data.target.internalPage.content.content.content[46].content[0].content[0].content[0].marks', line 30654, position 36.'
`

Pass the MaxDepth from the JsonSetting to the JsonConverter

---

Contentful.Core.Tests/ClientTestsBase.cs
Contentful.Core.Tests/Extensions/StringContentHelpers.cs
Contentful.Core.Tests/Search/QueryBuilderTests.cs
Contentful.Core.Tests/Search/SelectVisitorTests.cs
Contentful.Core/Contentful.Core.csproj
Contentful.Core/Search/ExpressionHelpers.cs
Contentful.Core/Search/QueryBuilder.cs
Contentful.Core/Search/SelectVisitor.cs

To implement per the HTTP API for selecting fields 
[API](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters)
but with a focus of applying as much of the validation through .Net exceptions as possible -- to limit runtime errors.
The main changes were:
* added the SelectFields calls to QueryBuilder<T>
* added tests covering every scenario that I thought of
* followed the spec on the API doc pages for the HTTP API
* added comments in code to ensure flow is manageable
* implemented an Expression Visitor to make use of the best practices for affecting and walking the Linq Expressions AST
I did add a comment that I had noticed the csproj file had the VersionPrefix set to 4.1.1, yet was using 7.2.2 on the effective fields below that.  If you …

Added SelectFields Method To QueryBuilder

---

Contentful.Core.Tests/JsonFiles/ContenttypesCollectionManagement.json
Contentful.Core/Models/Management/IFieldValidation.cs

This is a fix for #309. This currently breaks some of our customers in production, so I would appreciate it it someone can look at that and release a new version of the NuGet package fairly urgently 🙏

Correctly deserialize sub- and superscript enabled marks

---

.circleci/config.yml
Contentful.AspNetCore/Contentful.AspNetCore.csproj
Contentful.Core/Contentful.Core.csproj
Contentful.Core/ContentfulManagementClient.cs

This PR updates the Docker image used in the CircleCI pipeline, since the original `microsoft/aspnetcore-build:2.0` image is deprecated. The new image needs `ssh` and `git` to be installed, so this is added to the steps. Finally, a syntax error was fixed because the build was failing with an error `Invalid expression term '['`, so I changed the syntax to be valid in all modern C# versions.

fix: update CircleCI config and fix syntax error to make build pass []

---

CHANGELOG.md
Contentful.AspNetCore/Contentful.AspNetCore.csproj
Contentful.Core.Tests/ContentfulManagementClientTests.cs
Contentful.Core/Contentful.Core.csproj
Contentful.Core/ContentfulManagementClient.cs

Updating a role expects that the version is passed in as a header

fix: Add version header to UpdateRole method to fix ContentfulException
